import Welcome from "./Welcome";
import AccountPermission from "./AccountPermission";
import Loading from "./Loading";
import SyncAddress from "./SyncAddress";
import QrToSign from "./QrToSign";
import QrToRead from "./QrToRead";
import SendToChain from "./SendToChain";
import SwitchChain from "./SwitchChain";
import Send from "./Send";
